name: Deploy Docker to EC2

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Run Docker commands on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Pull the Docker image from Docker Hub (or any other registry)
          docker pull my-docker-image:latest
          
          # Stop and remove the existing container (if any)
          docker stop my-container || true
          docker rm my-container || true
          
          # Run the Docker container
          docker run -d --name my-container my-docker-image:latest
        EOF
